import { MenuItem, MealCategory, CuisineType } from '../types';

export const MENU_DATA: MenuItem[] = [
  { id: 1, name_th: 'ข้าวกะเพราไก่ไข่ดาว', name_en: 'Basil Chicken with Rice & Egg', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 630 },
  { id: 2, name_th: 'ส้มตำไทย', name_en: 'Thai Papaya Salad', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 120 },
  { id: 3, name_th: 'ต้มยำกุ้งน้ำข้น', name_en: 'Tom Yum Kung (Creamy)', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 350 },
  { id: 4, name_th: 'แกงเขียวหวานไก่', name_en: 'Green Curry Chicken', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 480 },
  { id: 5, name_th: 'ข้าวผัดหมู', name_en: 'Fried Rice with Pork', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 550 },
  { id: 6, name_th: 'ลาบหมู', name_en: 'Spicy Minced Pork Salad', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 150 },
  { id: 7, name_th: 'ผัดไทยกุ้งสด', name_en: 'Pad Thai with Prawns', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 500 },
  { id: 8, name_th: 'ก๋วยเตี๋ยวเรือหมู', name_en: 'Boat Noodles (Pork)', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 450 },
  { id: 9, name_th: 'ข้าวมันไก่ต้ม', name_en: 'Hainanese Chicken Rice', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 600 },
  { id: 10, name_th: 'ยำวุ้นเส้น', name_en: 'Spicy Glass Noodle Salad', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 180 },
  { id: 11, name_th: 'ปลานึ่งมะนาว', name_en: 'Steamed Fish with Lime', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 200 },
  { id: 12, name_th: 'ข้าวไข่เจียวหมูสับ', name_en: 'Omelet with Minced Pork', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 450 },
  { id: 13, name_th: 'สุกี้น้ำไก่', name_en: 'Suki Soup with Chicken', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 280 },
  { id: 14, name_th: 'ราดหน้าหมูหมัก', name_en: 'Noodles in Gravy Sauce', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 400 },
  { id: 15, name_th: 'ผัดซีอิ๊ว', name_en: 'Stir-fried Soy Sauce Noodles', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 520 },
  { id: 16, name_th: 'แกงจืดเต้าหู้หมูสับ', name_en: 'Clear Soup with Tofu', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 120 },
  { id: 17, name_th: 'น้ำพริกปลาทู + ผักลวก', name_en: 'Chili Paste with Mackerel', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 150 },
  { id: 18, name_th: 'ข้าวหมูแดง', name_en: 'BBQ Pork Rice', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 500 },
  { id: 19, name_th: 'ข้าวขาหมู', name_en: 'Stewed Pork Leg Rice', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 650 },
  { id: 20, name_th: 'ต้มข่าไก่', name_en: 'Chicken Galangal Soup', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 320 },
  { id: 21, name_th: 'ไก่ย่างวิเชียร', name_en: 'Grilled Chicken', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 220 },
  { id: 22, name_th: 'คั่วกลิ้งหมู', name_en: 'Dry Curry Pork', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 250 },
  { id: 23, name_th: 'มัสมั่นไก่', name_en: 'Chicken Massaman Curry', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 600 },
  { id: 24, name_th: 'หมูกระเทียมพริกไทย', name_en: 'Garlic Pork', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 450 },
  { id: 25, name_th: 'ข้าวคลุกกะปิ', name_en: 'Shrimp Paste Fried Rice', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 550 },
  { id: 26, name_th: 'เย็นตาโฟ', name_en: 'Yentafo Noodle Soup', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 350 },
  { id: 27, name_th: 'ก๋วยจั๊บน้ำข้น', name_en: 'Rolled Noodles Soup', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 420 },
  { id: 28, name_th: 'ข้าวซอยไก่', name_en: 'Khao Soi Chicken', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 500 },
  { id: 29, name_th: 'ยำมะม่วง', name_en: 'Spicy Mango Salad', category: MealCategory.SNACK, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 150 },
  { id: 30, name_th: 'ลูกชิ้นปิ้ง', name_en: 'Grilled Meatballs', category: MealCategory.SNACK, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 200 },
  { id: 31, name_th: 'ขนมจีบ', name_en: 'Dumplings', category: MealCategory.SNACK, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: false, calories_approx: 250 },
  { id: 32, name_th: 'ซาลาเปาไส้หมูสับ', name_en: 'Steamed Pork Bun', category: MealCategory.SNACK, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: false, calories_approx: 220 },
  { id: 33, name_th: 'ปอเปี๊ยะทอด', name_en: 'Fried Spring Rolls', category: MealCategory.SNACK, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: false, calories_approx: 300 },
  { id: 34, name_th: 'เต้าฮวยน้ำขิง', name_en: 'Tofu with Ginger Syrup', category: MealCategory.SNACK, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 150 },
  { id: 35, name_th: 'ผลไม้รวม', name_en: 'Mixed Fruits', category: MealCategory.SNACK, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 80 },
  { id: 36, name_th: 'ชานมไข่มุก', name_en: 'Bubble Milk Tea', category: MealCategory.BEVERAGE, cuisine: CuisineType.FUSION, is_healthy_option: false, calories_approx: 350 },
  { id: 37, name_th: 'กาแฟเย็น', name_en: 'Iced Coffee', category: MealCategory.BEVERAGE, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: false, calories_approx: 200 },
  { id: 38, name_th: 'ชาเขียวมัทฉะ (ไม่หวาน)', name_en: 'Matcha Green Tea (Unsweetened)', category: MealCategory.BEVERAGE, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: true, calories_approx: 10 },
  { id: 39, name_th: 'น้ำแตงโมปั่น', name_en: 'Watermelon Smoothie', category: MealCategory.BEVERAGE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 80 },
  { id: 40, name_th: 'น้ำเต้าหู้', name_en: 'Soy Milk', category: MealCategory.BEVERAGE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 120 },
  { id: 41, name_th: 'สลัดโรล', name_en: 'Salad Rolls', category: MealCategory.SNACK, cuisine: CuisineType.FUSION, is_healthy_option: true, calories_approx: 150 },
  { id: 42, name_th: 'แซนวิชทูน่า', name_en: 'Tuna Sandwich', category: MealCategory.SNACK, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: true, calories_approx: 250 },
  { id: 43, name_th: 'โยเกิร์ตพร้อมดื่ม', name_en: 'Drinking Yogurt', category: MealCategory.BEVERAGE, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: true, calories_approx: 120 },
  { id: 44, name_th: 'อกไก่ปั่น', name_en: 'Chicken Breast Smoothie', category: MealCategory.BEVERAGE, cuisine: CuisineType.FUSION, is_healthy_option: true, calories_approx: 180 },
  { id: 45, name_th: 'หมูปิ้งนมสด', name_en: 'Grilled Milk Pork', category: MealCategory.SNACK, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 250 },
  { id: 46, name_th: 'เกี๊ยวน้ำกุ้ง', name_en: 'Shrimp Wonton Soup', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.INTERNATIONAL, is_healthy_option: true, calories_approx: 200 },
  { id: 47, name_th: 'เส้นหมี่ลูกชิ้นน้ำใส', name_en: 'Clear Noodle Soup with Meatballs', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 300 },
  { id: 48, name_th: 'ข้าวหน้าปลาแกะ', name_en: 'Rice with Fried Fish', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 400 },
  { id: 49, name_th: 'ยำมาม่า', name_en: 'Spicy Instant Noodle Salad', category: MealCategory.MAIN_COURSE, cuisine: CuisineType.THAI, is_healthy_option: false, calories_approx: 350 },
  { id: 50, name_th: 'ไข่ต้ม', name_en: 'Boiled Egg', category: MealCategory.SNACK, cuisine: CuisineType.THAI, is_healthy_option: true, calories_approx: 75 },
];